### ISSUE TITLE
Wrong speed in minecarts?

### ISSUE THREAD

**Issue by T0biasCZe** [zaze06/Speedometer#1]
Minecraft version 1.20.4
Forge version
Speedometer 5.1
When riding in minecart, the speed shows as 41.08 Blocks per second. However, the max speed of minecart is 8 block per second
isnt there bug?
![image](https://github.com/zaze06/Speedometer/assets/44525446/40274487-b5b1-4703-a9d3-b4d4a0c645ba)

**Comment by zaze06** [comment]
Hi, Thanks.

That certainly is interesting, I will take a look at it.

**Comment by zaze06** [comment]
As it appears I have done the math wrong for magnifying the speed in the tested cases. I will get on to fixing this.

Apologizes for this issue but thanks for pointing it out.

**Comment by zaze06** [comment]
Fixed in version [5.2](https://modrinth.com/mod/speedometer/version/clZR3yTQ) for 1.20.X and 6.1 for 1.21.

Hope you have a good day.
