### ISSUE TITLE
[Bug Report, Please chage]

### ISSUE THREAD

**Issue by OMXSPI-index** [zaze06/Speedometer#2]
**What Happend**
Crash

**What was Expected**
Big meter

**Screen Shot(s)**
(Only if relevent)

**Versions**
- Minecraft:1.21.1
- Mod Loader:21.1.66
- Speedometer:6.2-dev
- Architectury:13.0.6

**Mod Loader**
- NeoForge

**Config**
*If needed*
*Use [GitHub Gist](gist.gihub.com) to upload your speedometer config, located in *

**Logs**
https://mclo.gs/2cAReUS

**Comment by zaze06** [comment]
Solved in 95222c1c952959a6f327a6ee8bb84e195c21445b and in version 6.2 release
