### ISSUE TITLE
Doesn't hide in F1

### ISSUE THREAD

**Issue by xllifi** [zaze06/Speedometer#3]
**What Happened**
Speedometer remains visible when F1 is toggled on.

**What was Expected**
Speedometer turns invisible when F1 is toggled on.

**Screenshots**
F1 toggled off:
![An image showing Flashback, WaterPlayer and Speedometer UI visible with F1 mode enabled](https://github.com/user-attachments/assets/20ad11a7-858c-42bc-bf95-0f2a30803082)
F1 toggled on:
![An image showing only Speedometer UI visible with F1 mode enabled](https://github.com/user-attachments/assets/36ac0ea6-bdec-4bbd-a99b-6f6935d912b8)

**Versions**
- Minecraft: 1.21
- Mod Loader: **Fabric** 0.15.11 (API 102.0)
- Speedometer: 6.2
- Architectury: 13.0.8

**Comment by zaze06** [comment]
Hi, Thanks for reporting this. This is an oversite on my part.

**Comment by zaze06** [comment]
Hi, hopefully this version fixed your issue [6.2.1](https://modrinth.com/mod/speedometer/version/6.2.1)
